Repository fhrf/fhrf.github.io, pull requests merged in 2020-10, with the labels that each got.

#17 Fixed typos in REadme.md
  README.md
Labels: documentation, hacktoberfest-accepted

#19 Fixing the footer
  about.html
Labels: hacktoberfest-accepted

#18 add lazy loading to events images
  scripts/load-events.js
Labels: enhancement, hacktoberfest-accepted
